apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-postzegel-backend-persistent-volume-claim
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: standard
  volumeName: postgres-postzegel-backend-persistent-volume
