apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgres-postzegel-backend-persistent-volume
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 1Gi
  storageClassName: standard
  hostPath:
    path: $PERSISTENT_VOLUME_PATH/postgres-postzegel-backend-persistent-volume
