apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: kafka-postzegel-reporter
spec:
  template:
    spec:
      containers:
      - image: apache/kafka:latest
        name: kafka-postzegel-reporter
        env:
        - name: KAFKA_NODE_ID
          value: "1"
        - name: KAFKA_PROCESS_ROLES
          value: broker,controller
        - name: KAFKA_LISTENERS
          value: PLAINTEXT://0.0.0.0:9092,CONTROLLER://:9093
        - name: KAFKA_ADVERTISED_LISTENERS
          value: PLAINTEXT://kafka-postzegel-reporter:9092
        - name: KAFKA_CONTROLLER_LISTENER_NAMES
          value: CONTROLLER
        - name: KAFKA_LISTENER_SECURITY_PROTOCOL_MAP
          value: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
        - name: KAFKA_CONTROLLER_QUORUM_VOTERS
          value: 1@:9093
        - name: KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR
          value: "1"
        - name: KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR
          value: "1"
        - name: KAFKA_TRANSACTION_STATE_LOG_MIN_ISR
          value: "1"
        - name: KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS
          value: "0"
        - name: KAFKA_NUM_PARTITIONS
          value: "3"
        ports:
        - containerPort: 9092
          # Limit of 15 characters for the name
          name: kafka-pb
        volumeMounts:
        - name: kafka-postzegel-reporter-data
          mountPath: /tmp/kafka-logs
      volumes:
      - name: kafka-postzegel-reporter-data
        persistentVolumeClaim:
          claimName: kafka-postzegel-reporter-persistent-volume-claim
