apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgres-postzegel-backend
spec:
  template:
    spec:
      containers:
      - image: postgres:17-alpine
        name: postgres-postzegel-backend
        env:
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: postgres-postzegel-backend-secret
              key: password
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: postgres-postzegel-backend-secret
              key: user
        - name: POSTGRES_DB
          value: postzegel-backend
        ports:
        - containerPort: 5432
          # Limit of 15 characters for the name
          name: postgres-pb
        volumeMounts:
        - name: postgres-postzegel-backend-data
          mountPath: /var/lib/postgresql/data
      volumes:
      - name: postgres-postzegel-backend-data
        persistentVolumeClaim:
          claimName: postgres-postzegel-backend-persistent-volume-claim
