kind: Service
apiVersion: v1
metadata:
  name: postzegel-backend-service
  
spec:
  type: LoadBalancer
  ports:
  - protocol: TCP
    # port running on docker desktop
    port: 31313
    # on pod
    targetPort: 8080
    # on host running ubuntu
    nodePort: 31313
