apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../base
patches:
- path: patch-deploy.yaml
- path: patch-configMap.yaml
labels:
- includeSelectors: true
  pairs:
    env: staging
