apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-persistent-volume
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 1Gi
  storageClassName: standard
  hostPath:
    path: /home/martijn/kube-pv/mysql-persistent-volume
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - cubi